moja-global/FLINT.Cloud

README.md, rest_api/Dockerfile, rest_api/app.py, rest_api/config/libs.base.simple.json, rest_api/config/logging.debug_on.conf, rest_api/config/point_example.json, rest_api/requirements.txt
Set up the basic project structure with endpoints: 
- help
- version
- help-section arg
- point_example from FLINT.example
Tested locally
...
=> Add basic rest api project

rest_api_gcbm/app.py, rest_api_gcbm/requirements.txt, rest_api_gcbm/run_distributed.py, rest_api_gcbm/static/swagger.json
Add GCBM new, upload, dynamic, download and list endpoints. 
- New: Starts a new simulation using title from the body. If existing simulation then ask them to check the list of simulations. 
- List: Returns array of all simulations
- Upload: Upload files for the simulation (title as param in body)
- Dynamic: Run simulation (title as param in body) and upload input and output in gcloud bucket 
- Download: Get signed downloadable links for input and output
Fixes # (issue)
...
=> add gcbm new, upload, list, dynamic and download endpoints with gcloud bucket support

docs/DevelopmentSetup/git_and_github_guide.rst, docs/DevelopmentSetup/index.rst, docs/conf.py, docs/index.rst, docs/prerequisites/git.rst, docs/prerequisites/index.rst, docs/requirements.txt
This is a sample readthedocs setup PR. Merging this for now to reflect on the readthedocs dashboard and to setup additional webhooks.
Fixes # (issue)
...
=> add sample readthedocs setup

rest_api_gcbm/app.py, rest_api_gcbm/app.yaml, rest_api_gcbm/requirements.txt
- 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
- Disable auto-index for security reasons. (Risk of credential exposure)
- Add health/readiness endpoints for App Engine
- Fix minor bug with URLs and increase the timeout to 30 minutes
- Use logging lib instead of print
- Add Pub/Sub based response to the dynamic endpoint
- Run moja.cli in a separate thread
...
=> Add Pub/Sub to dynamic endpoint

rest_api_gcbm/app.py
Add streamingpull for pub/sub to store status of run in json file. 
Fixes # (issue)
...
=> add streamingpull for pub/sub

docs/conf.py, layered/cloud-run/main.py, layered/compute-engine/main.py, layered/ingress/estimate_run_size.py, layered/ingress/main.py, rest_api_flint.example/app.py, rest_api_gcbm/app.py, rest_api_gcbm/run_distributed.py
Formatted Code using [Black](https://github.com/psf/black).
=> Format Code using Black

local/rest_api_gcbm/app.py, local/rest_api_gcbm/requirements.txt, rest_api_gcbm/app.py, rest_api_gcbm/requirements.txt
Fixes CORS error in  GCBM API
Fixes #34
=> Fix CORS errors in GCBM API

.github/workflows/docker-ci.yml, .github/workflows/lint.yml, layered/main.tf
This PR adds:
- Lints for code 
- Lints for Dockerfile
- Lints for Terraform
=> CI: Add a linting pipeline

.github/workflows/base.yml, local/rest_api_gcbm/Dockerfile, local/rest_api_gcbm/Dockerfile.flint, local/rest_api_gcbm/Dockerfile.gcbm
This PR:
- [Refactor Dockerfiles to use moja global images](https://github.com/moja-global/FLINT.Cloud/commit/e99de0bf0b09bc6304d587d102df0250c26ae64d)
- [Refactor base workflow to run once every month](https://github.com/moja-global/FLINT.Cloud/commit/c951cb2b5215b481839ba0cc49ebfdca9046f250)
=> Optimize Docker images 

layered/cloud-run/main.py, layered/compute-engine/main.py, layered/ingress/main.py
Instead of adding items to a dictionary just after creation, it should be refactored to add those items into the `dict` definition itself.
=> fix: Move dictionary inserts to its definition

.github/containerscan/allowedlist.yaml, local/rest_api_flint.example/requirements.txt
I have added versions to the dependencies to dependencies in requirements.txt
...
=> Add version to dependencies

.flake8, .github/workflows/docker.yml, .github/workflows/test.yml, .gitignore, layered/cloud-run/main.py, layered/compute-engine/main.py, layered/ingress/main.py, local/tests/test_rest_gcbm.py
Tests for GCBM REST API endpoints are not created. So this PR resolves it.
...
=> Tests for GCBM REST API end points

local/rest_api_gcbm/Dockerfile
Fixes #91
The Dockerfile is already used and tested. This PR just adds npm installation to it.
cc: @HarshCasper @aornugent
=> Adding npm to rest_api_gcbm/Dockerfile

.github/workflows/lint.yml, local/rest_api_flint.example/app.py, local/rest_api_gcbm/app.py, local/rest_api_gcbm/run_distributed.py
Added black formatter in the Github actions. Formatted python reformatted local/rest_api_flint.example/app.py, local/rest_api_gcbm/run_distributed.py, local/rest_api_gcbm/app.py
No tests required
...
=> Add Black formatting to the GitHub workflow

local/rest_api_gcbm/Dockerfile
This PR provides fixes the error produced on installing node, npm in the gcbm example Dockerfile
Fixes #108 
The image is built on making this change, it has been verified locally.
=> fix: npm installation in gcbm example Dockerfile

README.md
The PR resolves the issue#95
Fixes #95.
...
=> Resolves Issue#95

local/rest_api_flint.example/app.py
root endpoint added in  rest_api_flint.example
- [root endpoint added in api] New feature (non-breaking change which adds functionality)
...
=> feat root  endpoint added in rest_api_flint.example

local/rest_api_flint.example/app.py, local/tests/test_rest_example.py
Added test cases rest_api_flint.example endpoints
=> Added test_cases for rest_api_flint.example endpoint 

local/rest_api_gcbm/app.py
Fixes #146.
The new docstring includes appropriate description and info for the `gcbm_new` method.
=> fix: Correct the docstring for gcbm_new method

.flake8, local/rest_api_gcbm/app.py, local/tests/test_rest_gcbm.py
Created new endpoints to upload specific config files. As per the new FLINT-UI user will be able to upload config files separately. As per the discussion, we have decided to move forward with this implementation of the upload feature where a user has the ability to upload each file separately. Later each file from these folders will be used for pre processing.  
```
/upload/title
/upload/disturbances 
/upload/classifiers
/upload/miscellaneous
/upload/db
```
Tested all the endpoints locally. 
@Namyalg @padmajabhol @ankitaS11 please review.
=> feat: Added title and Upload endpoints for GCBM Simulation

provider/digital_ocean/rest_api_flint.example/README.md, provider/digital_ocean/rest_api_flint.example/main.tf, provider/digital_ocean/rest_api_flint.example/output.tf, provider/digital_ocean/rest_api_flint.example/variables.tf, provider/digital_ocean/rest_api_gcbm/README.md, provider/digital_ocean/rest_api_gcbm/main.tf, provider/digital_ocean/rest_api_gcbm/output.tf, provider/digital_ocean/rest_api_gcbm/variables.tf
A new terraform Provider is added for the FLINT Example. With the help of this script, the user will be able to deploy FLINT's docker image directly to the digital ocean. The user has to add a `do_token` to authenticate their account. 
A Readme.md file is also added for all the requirements and installation steps. 
- Container Image Used - https://registry.terraform.io/modules/christippett/container-server/cloudinit/latest
- Changes that will be made when the user runs `terraform apply`
=> feat: Added Terraform's Digital Ocean Provider for FLINT Example and GCBM

docker/Dockerfile.gcbm
Signed-off-by: Sukriti-sood <soodsukriti1111@gmail.com>
Added Dependencies:-
- DVC 
- mojadata 
Fixes #155 
I have tested the build locally
=> Added upstream dependencies to `flint.gcbm`

kubernetes/azure/README.md, kubernetes/azure/rest_api_flint.example/flint-api.yml, kubernetes/azure/rest_api_gcbm/flint-gcbm.yml
Added README.md file containing steps to deploy APIs on aks cluster.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #159
...
=> Added README.md for deployment of flint APIs on Azure Kubernetes Cluster

local/tests/test_rest_example.py
Pytests for Point and RothC were missing in the test file.
Fixes #161 
=> Added pytests for Point and RothC

local/rest_api_gcbm/curl.md
Signed-off-by: Clinton Mekwunye <mekwunyeclinton22@gmail.com>
Currently there are no curl commands for the getConfig endpoint in the curl.md file. This pull request adds 3 curl commands for the endpoint. 
Each command gets the configuration details for the specified file in the command and returns it in json. 
Fixes # (https://github.com/moja-global/FLINT.Cloud/issues/193)
All the curl commands were ran in terminal and gave the expected output. The screenshot below shows this
=> Docs: Update curl.md with getconfig endpoint
